# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date_discussion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('created_date_discussion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='usser_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user_account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.discussion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user_account'),
        ),
    ]
