# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_account_id',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='usser_account_id',
        ),
        migrations.DeleteModel(
            name='user_account',
        ),
    ]
